package com.oneil.wellness.walkplanner.notification;
import java.time.*;import org.springframework.stereotype.Service;
@Service public class NotificationService{
 private final NotificationScheduler scheduler;public NotificationService(NotificationScheduler scheduler){this.scheduler=scheduler;}
 public NotificationDecision evaluate(NotificationEvaluationRequest request){if(request==null||request.recommendation()==null||request.preferences()==null)return no("Recommendation data is incomplete.");var p=request.preferences();var r=request.recommendation();Instant now=request.evaluatedAt()==null?Instant.now():request.evaluatedAt();ZoneId zone=zone(request.timezone());Instant at=scheduler.scheduleAt(request);ZonedDateTime local=at.atZone(zone);if(!p.enabled())return no("Notifications are disabled.");if(!r.calendarAvailable())return no("Calendar conflict prevents this opportunity.");if(r.score()<p.minimumScore())return no("Recommendation score is below the notification threshold.");if(!p.notifyOnWeekends()&&(local.getDayOfWeek()==DayOfWeek.SATURDAY||local.getDayOfWeek()==DayOfWeek.SUNDAY))return no("Weekend notifications are disabled.");if(p.workingHoursOnly()&&(local.toLocalTime().isBefore(LocalTime.of(9,0))||!local.toLocalTime().isBefore(LocalTime.of(17,0))))return no("Outside working hours.");if(p.quietHoursEnabled()&&quiet(local.toLocalTime(),p.quietHoursStart(),p.quietHoursEnd()))return no("Quiet hours are active.");if(request.notificationsToday()>=p.maximumPerDay())return no("Daily notification limit reached.");if(request.lastNotificationAt()!=null&&request.lastNotificationAt().plusSeconds(p.cooldownMinutes()*60L).isAfter(now))return no("Notification cooldown is active.");if(at.isBefore(now.minusSeconds(60)))return no("The walking opportunity has already started.");String body="Score: "+r.score()+". "+r.reasonSummary()+" Your calendar is available until "+r.recommendedEnd().atZoneSameInstant(zone).toLocalTime()+".";return new NotificationDecision(true,at,"Eligible available recommendation.","Best walking opportunity starts in "+p.leadTimeMinutes()+" minutes.",body);}
 private boolean quiet(LocalTime time,LocalTime start,LocalTime end){if(start==null||end==null||start.equals(end))return false;return start.isBefore(end)?!time.isBefore(start)&&time.isBefore(end):!time.isBefore(start)||time.isBefore(end);}
 private NotificationDecision no(String reason){return new NotificationDecision(false,null,reason,null,null);}
 private ZoneId zone(String value){try{return value==null||value.isBlank()?ZoneId.systemDefault():ZoneId.of(value);}catch(DateTimeException e){return ZoneId.systemDefault();}}
}
