package com.oneil.wellness.walkplanner.calendar.credential;
import static org.junit.jupiter.api.Assertions.*;import com.oneil.wellness.walkplanner.calendar.model.CalendarProviderType;import com.oneil.wellness.walkplanner.calendar.persistence.*;import jakarta.persistence.EntityManager;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.annotation.Transactional;
@SpringBootTest(properties="provider.credentials.master-key=AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=") @Transactional
class EncryptedProviderCredentialStoreTest {
 @Autowired EncryptedProviderCredentialStore store;@Autowired ProviderCredentialReferenceRepository references;@Autowired ProviderEncryptedCredentialRepository values;@Autowired ProviderConnectionService connections;@Autowired JdbcTemplate jdbc;@Autowired EntityManager entityManager;UUID id;
 @BeforeEach void setup(){id=connections.getOrCreate(CalendarProviderType.GOOGLE,"Google",true).getId();}
 @Test void encryptsRotatesDeletesAndNeverPersistsPlaintext(){store.saveSecret(id,"access-token","plain-secret-value");assertEquals("plain-secret-value",store.readSecret(id,"access-token").orElseThrow());var first=values.findById(new ProviderEncryptedCredential.Key(id,"access-token")).orElseThrow();assertFalse(new String(first.getCiphertext()).contains("plain-secret-value"));int version=first.getCredentialVersion();store.rotateSecret(id,"access-token","rotated");assertEquals("rotated",store.readSecret(id,"access-token").orElseThrow());assertTrue(values.findById(new ProviderEncryptedCredential.Key(id,"access-token")).orElseThrow().getCredentialVersion()>version);store.deleteSecret(id,"access-token");assertFalse(store.exists(id,"access-token"));assertTrue(store.readSecret(id,"access-token").isEmpty());}
 @Test void rejectsWrongKeyAndTampering(){store.saveSecret(id,"refresh-token","sensitive");entityManager.flush();entityManager.clear();var wrong=new EncryptedProviderCredentialStore(references,values,"Hx4dHBsaGRgXFhUUExIREA8ODQwLCgkIBwYFBAMCAQA=");assertThrows(EncryptedProviderCredentialStore.CredentialStoreException.class,()->wrong.readSecret(id,"refresh-token"));jdbc.update("update provider_encrypted_credential set ciphertext=? where provider_connection_id=? and credential_key=?",new byte[]{1,2,3},id,"refresh-token");entityManager.clear();assertThrows(EncryptedProviderCredentialStore.CredentialStoreException.class,()->store.readSecret(id,"refresh-token"));}
}
