package com.oneil.wellness.walkplanner.activity;
import java.time.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class WalkActivityService{
 private final WalkActivityRepository repository;private final Clock clock=Clock.systemUTC();private final int maxMinutes;
 public WalkActivityService(WalkActivityRepository r,@Value("${walk.maximum-duration-minutes:480}")int m){repository=r;maxMinutes=m;}
 @Transactional public WalkActivity start(WalkRequest r){validateWindow(r);if(repository.findFirstByActivityStatus(ActivityStatus.ACTIVE).isPresent())throw new IllegalStateException("An active walk is already in progress.");return repository.save(WalkActivity.start(r,clock.instant()));}
 @Transactional public WalkActivity complete(UUID id,CompleteWalkRequest r){WalkActivity v=get(id);if(v.getActivityStatus()!=ActivityStatus.ACTIVE)throw new IllegalStateException("Only an active walk can be completed.");v.complete(r==null?new CompleteWalkRequest(null,false,null,null):r,clock.instant(),maxMinutes);return repository.save(v);}
 @Transactional public void cancel(UUID id){WalkActivity v=get(id);if(v.getActivityStatus()!=ActivityStatus.ACTIVE)throw new IllegalStateException("Only an active walk can be cancelled.");repository.delete(v);}
 @Transactional public WalkActivity manual(ManualWalkRequest r){if(r==null||r.actualStart()==null||r.durationMinutes()==null||r.durationMinutes()<1||r.durationMinutes()>maxMinutes)throw new IllegalArgumentException("A valid start and duration between 1 and "+maxMinutes+" minutes are required.");if(r.actualStart().plusMinutes(r.durationMinutes()).toInstant().isAfter(clock.instant()))throw new IllegalArgumentException("A completed walk cannot end in the future.");return repository.save(WalkActivity.manual(r,clock.instant()));}
 public List<WalkActivity> list(){return repository.findAllByOrderByOpportunityStartDesc();}public Optional<WalkActivity> active(){return repository.findFirstByActivityStatus(ActivityStatus.ACTIVE);}public WalkActivity get(UUID id){return repository.findById(id).orElseThrow(()->new NoSuchElementException("Walk activity was not found."));}@Transactional public void delete(UUID id){repository.delete(get(id));}private void validateWindow(WalkRequest r){if(r==null||r.opportunityStart()==null||r.opportunityEnd()==null||!r.opportunityStart().isBefore(r.opportunityEnd()))throw new IllegalArgumentException("A valid recommendation window is required.");}
}
