"use server";
import { evaluateNotification,fetchRecommendationHistory,recordRecommendationHistory } from "./lib/backend";import type { RecommendationSnapshot,UserSettings } from "./types";
import * as api from "./lib/backend";import type { HistoryRetention,PerceivedQuality,WellnessGoal } from "./types";
export async function saveRecommendationSnapshot(value:RecommendationSnapshot){try{return await recordRecommendationHistory(value);}catch{return null;}}
export async function getWellnessHistory(){try{return await fetchRecommendationHistory();}catch{return null;}}
export async function getNotificationDecision(value:RecommendationSnapshot,settings:UserSettings,last:string|null,count:number){try{return await evaluateNotification(value,settings,last,count);}catch{return {eligible:false,scheduleAt:null,reason:"Notification service is unavailable.",title:null,body:null};}}
export async function beginWalk(start:string,end:string){return api.startWalk(start,end)}export async function getActiveWalk(){try{return await api.activeWalk()}catch{return null}}export async function finishWalk(id:string,duration:number,partial:boolean,quality:PerceivedQuality|null,notes:string){return api.completeWalk(id,duration,partial,quality,notes)}export async function abandonWalk(id:string){return api.cancelWalk(id)}export async function getWalks(){try{return await api.listWalks()}catch{return []}}export async function addManualWalk(start:string,duration:number,quality:PerceivedQuality|null,notes:string){return api.manualWalk(start,duration,quality,notes)}export async function getGoal(){return api.fetchGoal()}export async function putGoal(v:WellnessGoal){return api.saveGoal(v)}export async function getGoalProgress(){try{return await api.fetchGoalProgress()}catch{return null}}export async function getRetention(){return api.fetchRetention()}export async function putRetention(v:HistoryRetention){return api.saveRetention(v)}
export async function classifyOpportunity(start:string,status:"skip"|"dismiss",source:"DASHBOARD"|"TIMELINE"|"NOTIFICATION"="DASHBOARD"){return api.recordOpportunityOutcome(start,status,source)}
export async function removeHistory(kind:"recommendations"|"notifications"|"activities"|"all",from?:string,to?:string){return api.deleteHistory(kind,from,to)}
