package com.oneil.wellness.walkplanner.dto;

import java.math.BigDecimal;

import com.oneil.wellness.walkplanner.recommendation.dto.WalkingRecommendationDto;

public record HourlyForecastPeriod(
        String startTime,
        BigDecimal temperature,
        BigDecimal actualTemperature,
        String temperatureUnit,
        String shortForecast,
        String iconUrl,
        BigDecimal precipitationProbability,
        BigDecimal humidity,
        BigDecimal windSpeed,
        String windDirection,
        Boolean isDaytime,
        BigDecimal feelsLikeTemperature,
        String feelsLikeMethod,
        BigDecimal uvIndex,
        String uvCategory,
        String uvObservationOrForecastTime,
        String uvSource,
        BigDecimal aqi,
        String aqiCategory,
        String aqiObservationTime,
        String aqiSource,
        String sunrise,
        String sunset,
        String daylightStatus,
        Integer remainingDaylightMinutes,
        WalkingRecommendationDto walkingRecommendation) {

    public HourlyForecastPeriod withWalkingRecommendation(WalkingRecommendationDto recommendation) {
        return new HourlyForecastPeriod(
                startTime,
                temperature,
                actualTemperature,
                temperatureUnit,
                shortForecast,
                iconUrl,
                precipitationProbability,
                humidity,
                windSpeed,
                windDirection,
                isDaytime,
                feelsLikeTemperature,
                feelsLikeMethod,
                uvIndex,
                uvCategory,
                uvObservationOrForecastTime,
                uvSource,
                aqi,
                aqiCategory,
                aqiObservationTime,
                aqiSource,
                sunrise,
                sunset,
                daylightStatus,
                remainingDaylightMinutes,
                recommendation);
    }

    public HourlyForecastPeriod withEnvironmentalData(
            BigDecimal feelsLikeTemperature,
            String feelsLikeMethod,
            BigDecimal uvIndex,
            String uvCategory,
            String uvObservationOrForecastTime,
            String uvSource,
            BigDecimal aqi,
            String aqiCategory,
            String aqiObservationTime,
            String aqiSource,
            String sunrise,
            String sunset,
            String daylightStatus,
            Integer remainingDaylightMinutes) {
        return new HourlyForecastPeriod(
                startTime,
                temperature,
                actualTemperature,
                temperatureUnit,
                shortForecast,
                iconUrl,
                precipitationProbability,
                humidity,
                windSpeed,
                windDirection,
                isDaytime,
                feelsLikeTemperature,
                feelsLikeMethod,
                uvIndex,
                uvCategory,
                uvObservationOrForecastTime,
                uvSource,
                aqi,
                aqiCategory,
                aqiObservationTime,
                aqiSource,
                sunrise,
                sunset,
                daylightStatus,
                remainingDaylightMinutes,
                walkingRecommendation);
    }
}
