package com.oneil.wellness.walkplanner.calendar.provider.google;
import com.fasterxml.jackson.databind.*;import com.oneil.wellness.walkplanner.calendar.credential.ProviderCredentialStore;import com.oneil.wellness.walkplanner.calendar.model.*;import com.oneil.wellness.walkplanner.calendar.persistence.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class GoogleTokenService {
 private final GoogleCalendarConfiguration config;private final GoogleHttpTransport http;private final ProviderConnectionService connections;private final ProviderCredentialStore credentials;private final OAuthTokenMetadataRepository metadata;private final ObjectMapper json=new ObjectMapper();private final Map<UUID,Object> locks=new ConcurrentHashMap<>();
 public GoogleTokenService(GoogleCalendarConfiguration c,GoogleHttpTransport h,ProviderConnectionService pcs,ProviderCredentialStore store,OAuthTokenMetadataRepository m){config=c;http=h;connections=pcs;credentials=store;metadata=m;}
 public String accessToken(){var connection=connections.find(CalendarProviderType.GOOGLE).orElseThrow(()->new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true));var meta=metadata.findById(connection.getId()).orElseThrow(()->new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true));if(meta.isRevoked())throw new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true);if(meta.getExpiresAt()==null||meta.getExpiresAt().isBefore(Instant.now().plusSeconds(60)))refresh(connection,meta);return credentials.readSecret(connection.getId(),"access-token").orElseThrow(()->new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true));}
 private void refresh(CalendarProviderConnection connection,OAuthTokenMetadata stale){synchronized(locks.computeIfAbsent(connection.getId(),k->new Object())){var current=metadata.findById(connection.getId()).orElse(stale);if(current.getExpiresAt()!=null&&current.getExpiresAt().isAfter(Instant.now().plusSeconds(60)))return;String refresh=credentials.readSecret(connection.getId(),"refresh-token").orElseThrow(()->required(connection));GoogleHttpTransport.Response response=null;for(int attempt=0;attempt<3;attempt++){response=http.exchange("POST",config.getTokenUri(),Map.of("Content-Type","application/x-www-form-urlencoded"),GoogleOAuthService.form(Map.of("client_id",config.getClientId(),"client_secret",config.getClientSecret(),"refresh_token",refresh,"grant_type","refresh_token")));if(response.status()!=429&&response.status()<500)break;if(attempt<2)try{Thread.sleep(100L*(attempt+1));}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}if(response==null||response.status()<200||response.status()>=300){connection.status(CalendarConnectionStatus.AUTHORIZATION_REQUIRED);throw required(connection);}try{JsonNode n=json.readTree(response.body());String access=n.path("access_token").asText();if(access.isBlank())throw required(connection);credentials.rotateSecret(connection.getId(),"access-token",access);String rotated=n.path("refresh_token").asText();if(!rotated.isBlank())credentials.rotateSecret(connection.getId(),"refresh-token",rotated);current.update(Instant.now().plusSeconds(n.path("expires_in").asLong(3600)),n.path("scope").asText(current.getScopes()),n.path("token_type").asText("Bearer"),true);metadata.save(current);connection.status(CalendarConnectionStatus.CONNECTED);}catch(GoogleProviderException e){throw e;}catch(Exception e){throw new GoogleProviderException("MALFORMED_RESPONSE","Google returned an invalid token response.");}}}
 private GoogleProviderException required(CalendarProviderConnection c){c.status(CalendarConnectionStatus.AUTHORIZATION_REQUIRED);return new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true);}
 @Transactional public void revoke(){connections.find(CalendarProviderType.GOOGLE).ifPresent(c->{try{credentials.readSecret(c.getId(),"refresh-token").ifPresent(token->http.exchange("POST",config.getRevocationUri(),Map.of("Content-Type","application/x-www-form-urlencoded"),"token="+GoogleOAuthService.url(token)));}catch(RuntimeException ignored){}finally{credentials.deleteAll(c.getId());metadata.findById(c.getId()).ifPresent(m->{m.revoke();metadata.save(m);});c.status(CalendarConnectionStatus.DISCONNECTED);}});}
 @Transactional public void disconnect(){connections.find(CalendarProviderType.GOOGLE).ifPresent(c->{credentials.deleteAll(c.getId());metadata.findById(c.getId()).ifPresent(m->{m.revoke();metadata.save(m);});c.status(CalendarConnectionStatus.DISCONNECTED);});}
 public Set<String> scopes(){return connections.find(CalendarProviderType.GOOGLE).flatMap(c->metadata.findById(c.getId())).map(m->Set.of(m.getScopes().split(" "))).orElse(Set.of());}
}
