package com.oneil.wellness.walkplanner.calendar.provider.google;
import com.fasterxml.jackson.databind.JsonNode;import com.oneil.wellness.walkplanner.calendar.*;import com.oneil.wellness.walkplanner.calendar.model.*;import com.oneil.wellness.walkplanner.calendar.persistence.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import java.util.concurrent.atomic.AtomicReference;import org.springframework.stereotype.Component;
@Component
public class GoogleCalendarProvider implements OAuthCalendarProvider {
 private final GoogleCalendarConfiguration config;private final GoogleOAuthService oauth;private final GoogleTokenService tokens;private final GoogleCalendarClient client;private final GoogleCalendarEventMapper mapper;private final ProviderConnectionService connections;private final AtomicReference<List<CalendarDescriptor>> calendars=new AtomicReference<>(List.of());private final Map<String,GoogleCalendar> providerCalendars=new java.util.concurrent.ConcurrentHashMap<>();private final AtomicReference<CalendarProviderSyncStatus> sync=new AtomicReference<>(CalendarProviderSyncStatus.never());
 public GoogleCalendarProvider(GoogleCalendarConfiguration c,GoogleOAuthService o,GoogleTokenService t,GoogleCalendarClient cl,GoogleCalendarEventMapper m,ProviderConnectionService pcs){config=c;oauth=o;tokens=t;client=cl;mapper=m;connections=pcs;}
 public CalendarProviderType getType(){return CalendarProviderType.GOOGLE;}public String getDisplayName(){return "Google Calendar";}public boolean isEnabled(){return config.isComplete();}public CalendarConnectionStatus getConnectionStatus(){if(!isEnabled())return CalendarConnectionStatus.DISABLED;return connections.find(getType()).map(CalendarProviderConnection::getConnectionStatus).orElse(CalendarConnectionStatus.DISCONNECTED);}public CalendarConnectionResult testConnection(){if(getConnectionStatus()!=CalendarConnectionStatus.CONNECTED)return new CalendarConnectionResult(getConnectionStatus(),"Google Calendar authorization is required.");try{discoverCalendars();return new CalendarConnectionResult(CalendarConnectionStatus.CONNECTED,"Google Calendar connection succeeded.");}catch(GoogleProviderException e){return new CalendarConnectionResult(e.isAuthorizationRequired()?CalendarConnectionStatus.AUTHORIZATION_REQUIRED:CalendarConnectionStatus.UNAVAILABLE,e.getMessage());}}
 public OAuthAuthorizationStart beginAuthorization(){return oauth.begin();}public OAuthAuthorizationResult completeAuthorization(String code,String state,String error){return oauth.complete(code,state,error);}public void revokeAuthorization(){tokens.revoke();calendars.set(List.of());providerCalendars.clear();}public Set<String> getGrantedScopes(){return tokens.scopes();}
 public CalendarDiscoveryResult discoverCalendars(){if(!isEnabled())return new CalendarDiscoveryResult(List.of(),"DISABLED","Google Calendar is disabled.",Instant.now());Set<String> persisted=connections.selectedIds(getType());List<CalendarDescriptor> result=new ArrayList<>();providerCalendars.clear();for(JsonNode n:client.listCalendars()){String actual=n.path("id").asText(),id=opaque(actual),name=n.path("summaryOverride").asText(n.path("summary").asText("Calendar")),role=n.path("accessRole").asText("reader"),zone=n.path("timeZone").asText("UTC");boolean primary=n.path("primary").asBoolean(false),selected=persisted.isEmpty()?primary:persisted.contains(id),readOnly=!Set.of("owner","writer").contains(role);providerCalendars.put(id,new GoogleCalendar(actual,zone));result.add(new CalendarDescriptor(getType(),id,name,null,true,readOnly,true,selected,n.path("backgroundColor").asText(null),primary?"Primary calendar":null));}calendars.set(List.copyOf(result));connections.persistSelections(getType(),result,result.stream().filter(CalendarDescriptor::selected).map(CalendarDescriptor::calendarId).collect(java.util.stream.Collectors.toSet()));connections.updateStatus(getType(),CalendarConnectionStatus.CONNECTED,false);return new CalendarDiscoveryResult(result,"DISCOVERED","Discovered "+result.size()+" Google calendar(s).",Instant.now());}
 public List<CalendarDescriptor> listCalendars(){return calendars.get().isEmpty()?discoverCalendars().calendars():calendars.get();}public List<CalendarDescriptor> selectCalendars(List<String> ids){Set<String> selected=Set.copyOf(ids==null?List.of():ids);List<CalendarDescriptor> available=listCalendars();if(!available.stream().map(CalendarDescriptor::calendarId).collect(java.util.stream.Collectors.toSet()).containsAll(selected))throw new GoogleProviderException("UNKNOWN_CALENDAR","One or more Google calendars are unavailable.");List<CalendarDescriptor> updated=available.stream().map(c->c.withSelected(selected.contains(c.calendarId()))).toList();calendars.set(updated);connections.persistSelections(getType(),updated,selected);return updated;}public List<CalendarDescriptor> getSelectedCalendars(){return listCalendars().stream().filter(CalendarDescriptor::selected).toList();}
 public List<CalendarEvent> fetchEvents(OffsetDateTime start,OffsetDateTime end){return getSelectedCalendars().stream().flatMap(c->fetchEvents(c,start,end).stream()).toList();}public List<CalendarEvent> fetchEvents(CalendarDescriptor calendar,OffsetDateTime start,OffsetDateTime end){Instant attempt=Instant.now();try{GoogleCalendar source=providerCalendars.get(calendar.calendarId());if(source==null){discoverCalendars();source=providerCalendars.get(calendar.calendarId());}if(source==null)throw new GoogleProviderException("UNKNOWN_CALENDAR","Google calendar is unavailable.");GoogleCalendar resolved=source;List<CalendarEvent> events=client.listEvents(resolved.providerId,start,end).stream().map(n->mapper.map(n,calendar.calendarId(),resolved.timezone)).flatMap(Optional::stream).toList();connections.updateStatus(getType(),CalendarConnectionStatus.CONNECTED,true);sync.set(new CalendarProviderSyncStatus(attempt,Instant.now(),"SUCCESS","Calendar synchronized.",List.of(new CalendarSynchronizationDetail(getType(),calendar.calendarId(),"SUCCESS",events.size(),null,"Calendar synchronized."))));return events;}catch(GoogleProviderException e){connections.updateStatus(getType(),e.isAuthorizationRequired()?CalendarConnectionStatus.AUTHORIZATION_REQUIRED:CalendarConnectionStatus.UNAVAILABLE,false);throw e;}}
 public CalendarProviderCapabilities getCapabilities(){return CalendarProviderCapabilities.readOnly(true,true);}public CalendarProviderSyncStatus getSyncStatus(){return sync.get();}public void disconnect(){tokens.disconnect();calendars.set(List.of());providerCalendars.clear();}private String opaque(String value){try{return "gcal_"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)),0,8);}catch(Exception e){throw new IllegalStateException(e);}}private record GoogleCalendar(String providerId,String timezone){}
 public boolean isInstallationConfigured(){return config.isComplete();}public int getDiscoveredCalendarCount(){return calendars.get().size();}public int getSelectedCalendarCount(){return calendars.get().isEmpty()?connections.selectedIds(getType()).size():(int)calendars.get().stream().filter(CalendarDescriptor::selected).count();}
}
