package com.oneil.wellness.walkplanner.calendar.provider.google;
import com.fasterxml.jackson.databind.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.OffsetDateTime;import java.util.*;import org.springframework.stereotype.Component;
@Component
public class GoogleCalendarClient {
 private final GoogleCalendarConfiguration config;private final GoogleHttpTransport http;private final GoogleTokenService tokens;private final ObjectMapper json=new ObjectMapper();
 public GoogleCalendarClient(GoogleCalendarConfiguration c,GoogleHttpTransport h,GoogleTokenService t){config=c;http=h;tokens=t;}
 public List<JsonNode> listCalendars(){List<JsonNode> result=new ArrayList<>();String page=null;do{Map<String,String> q=new LinkedHashMap<>();q.put("maxResults","250");if(page!=null)q.put("pageToken",page);JsonNode root=get("/users/me/calendarList",q);root.path("items").forEach(result::add);page=root.path("nextPageToken").asText(null);}while(page!=null);return result;}
 public List<JsonNode> listEvents(String calendarId,OffsetDateTime start,OffsetDateTime end){List<JsonNode> result=new ArrayList<>();String page=null;do{Map<String,String> q=new LinkedHashMap<>();q.put("timeMin",start.toInstant().toString());q.put("timeMax",end.toInstant().toString());q.put("singleEvents","true");q.put("showDeleted","true");q.put("maxResults","2500");if(page!=null)q.put("pageToken",page);JsonNode root=get("/calendars/"+GoogleOAuthService.url(calendarId)+"/events",q);root.path("items").forEach(n->{if(result.size()>=config.getMaximumEventsPerCalendar())throw new GoogleProviderException("EVENT_LIMIT_EXCEEDED","Google calendar returned too many events.");result.add(n);});page=root.path("nextPageToken").asText(null);}while(page!=null);return result;}
 private JsonNode get(String path,Map<String,String> query){URI uri=URI.create(config.getApiBaseUrl()+path+"?"+GoogleOAuthService.form(query));for(int attempt=0;attempt<3;attempt++){var response=http.exchange("GET",uri,Map.of("Authorization","Bearer "+tokens.accessToken(),"Accept","application/json"),null);if(response.status()>=200&&response.status()<300)try{return json.readTree(response.body());}catch(Exception e){throw new GoogleProviderException("MALFORMED_RESPONSE","Google Calendar returned invalid data.");}if(response.status()==401)throw new GoogleProviderException("AUTHORIZATION_REQUIRED","Google Calendar authorization is required.",true);if(response.status()==403)throw new GoogleProviderException("FORBIDDEN","Google Calendar access was rejected.");if(response.status()!=429&&response.status()<500)throw new GoogleProviderException("PROVIDER_ERROR","Google Calendar request failed.");if(attempt<2)try{Thread.sleep(100L*(attempt+1));}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}throw new GoogleProviderException("RATE_LIMITED","Google Calendar is temporarily unavailable.");}
}
