package com.oneil.wellness.walkplanner.calendar.provider.google;
import com.fasterxml.jackson.databind.*;import com.oneil.wellness.walkplanner.calendar.credential.ProviderCredentialStore;import com.oneil.wellness.walkplanner.calendar.model.*;import com.oneil.wellness.walkplanner.calendar.persistence.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class GoogleOAuthService {
 public static final String CALENDAR_LIST_SCOPE="https://www.googleapis.com/auth/calendar.calendarlist.readonly",EVENT_SCOPE="https://www.googleapis.com/auth/calendar.events.readonly";
 private final GoogleCalendarConfiguration config;private final GoogleHttpTransport http;private final OAuthAuthorizationStateRepository states;private final OAuthTokenMetadataRepository metadata;private final ProviderConnectionService connections;private final ProviderCredentialStore credentials;private final ObjectMapper json=new ObjectMapper();private final SecureRandom random=new SecureRandom();private final String successUrl,failureUrl;
 public GoogleOAuthService(GoogleCalendarConfiguration c,GoogleHttpTransport h,OAuthAuthorizationStateRepository s,OAuthTokenMetadataRepository m,ProviderConnectionService pcs,ProviderCredentialStore store,@Value("${calendar.oauth.frontend-success-url}")String success,@Value("${calendar.oauth.frontend-failure-url}")String failure){config=c;http=h;states=s;metadata=m;connections=pcs;credentials=store;successUrl=validateFrontend(success);failureUrl=validateFrontend(failure);}
 @Transactional public OAuthAuthorizationStart begin(){if(!config.isComplete())throw new GoogleProviderException("NOT_CONFIGURED","Google Calendar is disabled or incomplete.");var connection=connections.getOrCreate(CalendarProviderType.GOOGLE,"Google Calendar",true);String state=random(32),hash=sha256(state),verifier=random(48);credentials.saveSecret(connection.getId(),"oauth-state:"+hash,verifier);Instant expiry=Instant.now().plus(Duration.ofMinutes(10));states.save(new OAuthAuthorizationStateEntity(hash,CalendarProviderType.GOOGLE,"credential-reference",successUrl,expiry));connection.status(CalendarConnectionStatus.AUTHORIZATION_PENDING);String challenge=base64(sha256Bytes(verifier));String query=form(Map.of("client_id",config.getClientId(),"redirect_uri",config.getRedirectUri().toString(),"response_type","code","scope",CALENDAR_LIST_SCOPE+" "+EVENT_SCOPE,"access_type","offline","include_granted_scopes","true","state",state,"code_challenge",challenge,"code_challenge_method","S256","prompt","consent"));return new OAuthAuthorizationStart(config.getAuthorizationUri()+"?"+query,expiry.toString());}
 @Transactional public OAuthAuthorizationResult complete(String code,String rawState,String error){if(rawState==null||rawState.isBlank())return failure("INVALID_STATE","OAuth state is invalid.");String hash=sha256(rawState);var state=states.findForUpdate(hash).orElse(null);if(state==null||state.isUsed()||state.getExpiresAt().isBefore(Instant.now())||state.getProviderType()!=CalendarProviderType.GOOGLE)return failure("INVALID_STATE","OAuth state is invalid or expired.");state.consume();var connection=connections.getOrCreate(CalendarProviderType.GOOGLE,"Google Calendar",true);String key="oauth-state:"+hash;Optional<String> storedVerifier=credentials.readSecret(connection.getId(),key);credentials.deleteSecret(connection.getId(),key);if(storedVerifier.isEmpty())return failure("INVALID_STATE","OAuth state is invalid or expired.");String verifier=storedVerifier.get();if(error!=null||code==null||code.isBlank()){connection.status(CalendarConnectionStatus.DISCONNECTED);return failure("AUTHORIZATION_CANCELLED","Google authorization was cancelled.");}
  GoogleHttpTransport.Response response;try{response=http.exchange("POST",config.getTokenUri(),Map.of("Content-Type","application/x-www-form-urlencoded"),form(Map.of("client_id",config.getClientId(),"client_secret",config.getClientSecret(),"code",code,"code_verifier",verifier,"grant_type","authorization_code","redirect_uri",config.getRedirectUri().toString())));}catch(GoogleProviderException ex){connection.status(CalendarConnectionStatus.UNAVAILABLE);return failure("TOKEN_EXCHANGE_FAILED","Google authorization could not be completed.");}if(response.status()<200||response.status()>=300){connection.status(CalendarConnectionStatus.AUTHORIZATION_REQUIRED);return failure("TOKEN_EXCHANGE_FAILED","Google authorization could not be completed.");}try{JsonNode node=json.readTree(response.body());String scopes=node.path("scope").asText();Set<String> granted=Set.of(scopes.split(" "));if(!granted.containsAll(Set.of(CALENDAR_LIST_SCOPE,EVENT_SCOPE))){connection.status(CalendarConnectionStatus.AUTHORIZATION_REQUIRED);return failure("INSUFFICIENT_SCOPE","Required read-only calendar scopes were not granted.");}String access=node.path("access_token").asText();String refresh=node.path("refresh_token").asText();if(access.isBlank()||refresh.isBlank())return failure("TOKEN_EXCHANGE_FAILED","Google did not return reusable authorization.");credentials.saveSecret(connection.getId(),"access-token",access);credentials.saveSecret(connection.getId(),"refresh-token",refresh);Instant expiry=Instant.now().plusSeconds(node.path("expires_in").asLong(3600));metadata.save(new OAuthTokenMetadata(connection.getId(),expiry,scopes,node.path("token_type").asText("Bearer")));connection.status(CalendarConnectionStatus.CONNECTED);return new OAuthAuthorizationResult(true,successUrl,"CONNECTED","Google Calendar connected.");}catch(Exception ex){connection.status(CalendarConnectionStatus.AUTHORIZATION_REQUIRED);return failure("MALFORMED_RESPONSE","Google returned an invalid authorization response.");}}
 private OAuthAuthorizationResult failure(String status,String message){return new OAuthAuthorizationResult(false,failureUrl+"&reason="+url(status),status,message);}
 private String validateFrontend(String value){URI uri=URI.create(value);if(!Set.of("http","https").contains(uri.getScheme())||uri.getHost()==null)throw new IllegalStateException("OAuth frontend redirect must be an absolute HTTP(S) URL.");return value;}
 static String form(Map<String,String> values){return values.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->url(e.getKey())+"="+url(e.getValue())).collect(java.util.stream.Collectors.joining("&"));}static String url(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8);}private String random(int bytes){byte[] v=new byte[bytes];random.nextBytes(v);return base64(v);}private static String base64(byte[] v){return Base64.getUrlEncoder().withoutPadding().encodeToString(v);}private static byte[] sha256Bytes(String v){try{return MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}private static String sha256(String v){return java.util.HexFormat.of().formatHex(sha256Bytes(v));}
}
