"use client";

import { useEffect, useState } from "react";
import type { CalendarDescriptor, CalendarEvent, CalendarProvider } from "../types";
import { connectGoogleCalendar, disconnectProvider, discoverCalendars, discoverGoogleCalendars, getCalendarProviderSnapshot, getCalendarSyncStatus, revokeProvider, selectCalendars, selectGoogleCalendars, synchronizeCalendar, testConnection } from "../calendar-actions";
import { saveExternalCalendarEvents } from "./calendar-service";

type Props = { initialProviders?: CalendarProvider[]; providersAvailable?: boolean; manualEvents: CalendarEvent[]; onEvents: (events: CalendarEvent[]) => void };
const redirectUri="http://localhost:9090/api/calendar/providers/GOOGLE/oauth/callback";

export function CalendarConnections({ initialProviders = [], providersAvailable = true, manualEvents, onEvents }: Props) {
  const [providers,setProviders]=useState(initialProviders);const [available,setAvailable]=useState(providersAvailable);const [calendars,setCalendars]=useState<CalendarDescriptor[]>([]);const [googleCalendars,setGoogleCalendars]=useState<CalendarDescriptor[]>([]);
  const [message,setMessage]=useState(providersAvailable?"":"Calendar connections are temporarily unavailable. Manual events can still be used.");const [state,setState]=useState("");const [loading,setLoading]=useState<string|null>(null);const [lastAttempt,setLastAttempt]=useState<string|null>(null);const [lastSuccess,setLastSuccess]=useState<string|null>(null);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const oauth=params.get("oauth");if(!oauth)return;const reason=params.get("reason");if(oauth==="success"){setMessage("Google Calendar connected successfully. Discover calendars to choose availability sources.");void refresh(true);}else if(reason==="AUTHORIZATION_CANCELLED")setMessage("Google authorization was cancelled. Try connecting again.");else setMessage("Google authorization was not completed. Try connecting again.");window.history.replaceState({},"",window.location.pathname+window.location.hash);},[]);
  const caldav=providers.find(provider=>provider.type==="CALDAV");const google=providers.find(provider=>provider.type==="GOOGLE");
  async function perform(name:string,action:()=>Promise<void>){setLoading(name);setMessage("");try{await action();}catch{setState("ERROR");setMessage("Calendar operation could not be completed. Manual events are still available.");}finally{setLoading(null);}}
  async function refresh(preserveMessage=false){const snapshot=await getCalendarProviderSnapshot();setProviders(snapshot.providers);setAvailable(snapshot.available);if(!preserveMessage)setMessage(snapshot.message??"");}
  function test(){return perform("caldav-test",async()=>{const result=await testConnection("CALDAV");setState(result.status);setMessage(result.message);await refresh(true);});}
  function discover(){return perform("caldav-discovery",async()=>{const result=await discoverCalendars();setCalendars(result.calendars);setProviders(current=>current.map(p=>p.type==="CALDAV"?{...p,discoveredCalendarCount:result.calendars.length,selectedCalendarCount:result.calendars.filter(c=>c.selected).length}:p));setState(result.status);setMessage(result.message);});}
  function toggle(id:string){setCalendars(current=>current.map(calendar=>calendar.calendarId===id?{...calendar,selected:!calendar.selected}:calendar));}
  function applySelection(){return perform("caldav-selection",async()=>{const selected=calendars.filter(calendar=>calendar.selected).map(calendar=>calendar.calendarId);const result=await selectCalendars(selected);setCalendars(result);setProviders(current=>current.map(p=>p.type==="CALDAV"?{...p,selectedCalendarCount:selected.length}:p));setMessage(selected.length?"Calendar selection saved.":"Select at least one calendar.");});}
  function sync(){return perform("sync",async()=>{setLastAttempt(new Date().toISOString());const result=await synchronizeCalendar(manualEvents);onEvents(saveExternalCalendarEvents(result.events));const status=await getCalendarSyncStatus();setLastAttempt(status.lastAttempt??result.synchronizedAt);setLastSuccess(status.lastSuccess);setState(result.partial?"PARTIAL":"SUCCESS");setMessage(result.errors.length?result.errors[0].message:"Synchronized successfully.");});}
  function disconnect(type:"CALDAV"|"GOOGLE",revoke=false){return perform(`${type}-disconnect`,async()=>{await (revoke?revokeProvider(type):disconnectProvider(type));await refresh(true);if(type==="GOOGLE")setGoogleCalendars([]);else setCalendars([]);setMessage(revoke?"Google authorization revoked.":`${type==="GOOGLE"?"Google Calendar":"CalDAV"} disconnected.`);});}
  function connectGoogle(){setState("CONNECTING");return perform("google-connect",async()=>{const result=await connectGoogleCalendar();if(!result.authorizationUrl){setState("ERROR");setMessage("Google Calendar authorization is temporarily unavailable. Try again.");return;}window.location.assign(result.authorizationUrl);});}
  function discoverGoogle(){return perform("google-discovery",async()=>{const result=await discoverGoogleCalendars();setGoogleCalendars(result.calendars);setProviders(current=>current.map(p=>p.type==="GOOGLE"?{...p,discoveredCalendarCount:result.calendars.length,selectedCalendarCount:result.calendars.filter(c=>c.selected).length}:p));setState(result.status);setMessage(result.message);});}
  function toggleGoogle(id:string){setGoogleCalendars(current=>current.map(c=>c.calendarId===id?{...c,selected:!c.selected}:c));}
  function applyGoogleSelection(){return perform("google-selection",async()=>{const selected=googleCalendars.filter(c=>c.selected).map(c=>c.calendarId);const result=await selectGoogleCalendars(selected);setGoogleCalendars(result);setProviders(current=>current.map(p=>p.type==="GOOGLE"?{...p,selectedCalendarCount:selected.length}:p));setMessage("Google calendar selection saved.");});}
  const caldavConnected=Boolean(caldav?.connected||caldav?.status==="CONNECTED");const caldavNeedsConfiguration=caldav?.status==="CONFIGURATION_REQUIRED";const googleConnected=Boolean(google?.connected||google?.status==="CONNECTED");const googleConfigured=google?.installationConfigured??google?.enabled??false;
  const googleDisplayStatus=state==="CONNECTING"||google?.status==="AUTHORIZATION_PENDING"?"CONNECTING":googleConfigured&&google?.status==="DISCONNECTED"?"READY TO CONNECT":google?.providerStatus??google?.status??(available?"DISABLED":"UNAVAILABLE");
  const active=["Manual Calendar",...(caldavConnected?[`CalDAV${caldav?.selectedCalendarCount?`: ${caldav.selectedCalendarCount} selected`:""}`]:[]),...(googleConnected?[`Google Calendar${google?.selectedCalendarCount?`: ${google.selectedCalendarCount} selected`:""}`]:[])];
  return <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-label="Calendar Connections" aria-busy={loading!==null}>
    <h2 className="text-xl font-semibold">Calendar Connections</h2><p className="mt-1 text-sm text-slate-600">Account authorization happens here. Installation credentials and encrypted provider tokens remain on the backend and are never stored in this browser.</p>
    <div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold">{active.length} calendar {active.length===1?"source":"sources"} active</p><ul className="mt-1 text-sm text-slate-600">{active.map(value=><li key={value}>{value}</li>)}</ul></div>
    {!available?<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p role="alert" className="text-sm text-amber-900">Calendar connections are temporarily unavailable. Manual events can still be used.</p><button type="button" onClick={()=>perform("retry",refresh)} disabled={loading!==null} className="mt-3 rounded-xl border border-amber-400 bg-white px-3 py-1.5 text-sm font-semibold">Retry calendar connections</button></div>:null}
    <div className="mt-5 grid items-start gap-3 lg:grid-cols-2">
      <Provider name="Manual Calendar" status="Connected" detail="Device-local · no external connection required" />
      <Provider name="CalDAV" status={caldav?.providerStatus??caldav?.status??(available?"CONFIGURATION_REQUIRED":"UNAVAILABLE")} detail={!caldav?.enabled||caldavNeedsConfiguration?"CalDAV requires server configuration, including the provider credential master key.":caldavConnected?`Connected · read-only availability · ${caldav?.selectedCalendarCount??0} calendars selected`:"CalDAV is disconnected."}>
        {!caldav?.enabled||caldavNeedsConfiguration?<span className="text-xs text-slate-500">Configure through server settings</span>:!caldavConnected?<Action onClick={test} loading={loading}>Test connection</Action>:<><CalendarChoices legend="Calendars" calendars={calendars} toggle={toggle} apply={applySelection} applyLabel="Apply selection" loading={loading!==null}/>{caldavConnected&&state==="NO_CALENDARS"?<p className="text-sm text-slate-600">No CalDAV calendars were discovered.</p>:null}<div className="flex flex-wrap gap-2"><Action onClick={discover} loading={loading}>Discover calendars</Action><Action onClick={sync} loading={loading} disabled={!calendars.some(c=>c.selected)&&!(caldav?.selectedCalendarCount)}>Synchronize now</Action></div><SyncTime provider={caldav} attempt={lastAttempt} success={lastSuccess}/><details className="text-sm"><summary className="cursor-pointer font-medium">Advanced</summary><Action onClick={()=>disconnect("CALDAV")} loading={loading}>Disconnect CalDAV</Action></details></>}
      </Provider>
      <Provider name="Google Calendar" status={googleDisplayStatus} detail={!googleConfigured?"Google Calendar is not configured for this Wellness Window installation.":googleConnected?`Connected · read-only availability · ${google?.selectedCalendarCount??0} calendars selected`:google?.authorizationRequired||google?.status==="AUTHORIZATION_REQUIRED"?"Authorization is required.":state==="CONNECTING"?"Redirecting securely to Google…":"Ready for account authorization."}>
        {!googleConfigured?<details><summary className="cursor-pointer text-sm font-semibold text-blue-700">Setup instructions</summary><div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><p>Google Calendar requires a Google Cloud OAuth client configured by the Wellness Window administrator.</p><p className="mt-2">Required server values: client ID, client secret, redirect URI, and encryption master key. For security, these values cannot be entered or viewed in this browser.</p><p className="mt-2 font-medium">Expected redirect URI</p><code className="mt-1 block break-all text-xs">{redirectUri}</code><p className="mt-3 text-xs">See the Google Calendar setup section in the project README or <code>docs/google-calendar.md</code>.</p></div></details>:googleConnected?<><CalendarChoices legend="Calendars" calendars={googleCalendars} toggle={toggleGoogle} apply={applyGoogleSelection} applyLabel="Apply Google selection" loading={loading!==null}/>{googleConnected&&state==="NO_CALENDARS"?<p className="text-sm text-slate-600">No Google calendars were discovered.</p>:null}<div className="flex flex-wrap gap-2"><Action onClick={discoverGoogle} loading={loading}>Discover calendars</Action><Action onClick={sync} loading={loading} disabled={!googleCalendars.some(c=>c.selected)&&!(google?.selectedCalendarCount)}>Synchronize now</Action><Action onClick={()=>disconnect("GOOGLE")} loading={loading}>Disconnect Google</Action></div><SyncTime provider={google} attempt={lastAttempt} success={lastSuccess}/><details className="text-sm"><summary className="cursor-pointer font-medium">Advanced</summary><button type="button" onClick={()=>disconnect("GOOGLE",true)} disabled={loading!==null} className="mt-2 rounded-xl border border-red-200 px-3 py-1.5 font-semibold text-red-700">Revoke Google access</button></details></>:<Action primary onClick={connectGoogle} loading={loading}>{google?.authorizationRequired||google?.status==="AUTHORIZATION_REQUIRED"?"Reconnect Google Calendar":message.includes("not completed")||state==="ERROR"?"Try again":"Connect Google Calendar"}</Action>}
      </Provider>
      <Provider name="Microsoft Calendar" status="COMING LATER" detail="Coming later" />
    </div>
    {loading?<p role="status" aria-live="polite" className="mt-4 text-sm">{loading.includes("discovery")?"Discovering calendars…":loading==="sync"?"Synchronizing calendars…":loading==="google-connect"?"Connecting to Google…":"Updating calendar connection…"}</p>:null}
    {message?<p role={state==="ERROR"?"alert":"status"} aria-live="polite" className="mt-3 text-sm text-slate-700">{message}</p>:null}
  </section>;
}

function Provider({name,status,detail,children}:{name:string;status:string;detail:string;children?:React.ReactNode}){return <article className="min-w-0 rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{name}</h3><span className="text-xs font-semibold uppercase text-slate-600" aria-label={`${name} status: ${status}`}>{status.replaceAll("_"," ")}</span></div><p className="mt-1 text-sm text-slate-600">{detail}</p>{children?<div className="mt-4 space-y-3">{children}</div>:null}</article>}
function Action({children,onClick,loading,disabled=false,primary=false}:{children:React.ReactNode;onClick:()=>void;loading:string|null;disabled?:boolean;primary?:boolean}){return <button type="button" onClick={onClick} disabled={loading!==null||disabled} className={`${primary?"bg-blue-700 text-white":"border border-slate-300"} rounded-xl px-3 py-1.5 text-sm font-semibold disabled:opacity-50`}>{children}</button>}
function CalendarChoices({legend,calendars,toggle,apply,applyLabel,loading}:{legend:string;calendars:CalendarDescriptor[];toggle:(id:string)=>void;apply:()=>void;applyLabel:string;loading:boolean}){if(!calendars.length)return null;return <fieldset className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 text-sm font-semibold">{legend}</legend><div className="space-y-3">{calendars.map(calendar=><label key={calendar.calendarId} className="flex items-start gap-3"><input type="checkbox" checked={calendar.selected} disabled={!calendar.supportsEvents} onChange={()=>toggle(calendar.calendarId)}/><span><span className="font-medium">{calendar.displayName}</span>{calendar.description?.toLowerCase().includes("primary")?<span className="ml-2 text-xs font-semibold uppercase text-blue-700">Primary</span>:null}{calendar.readOnly?<span className="ml-2 text-xs uppercase text-slate-500">Read only</span>:null}{calendar.description?<span className="block text-xs text-slate-500">{calendar.description}</span>:null}</span></label>)}</div><button type="button" onClick={apply} disabled={loading} className="mt-4 rounded-xl border border-slate-300 px-3 py-1.5 text-sm font-semibold disabled:opacity-50">{applyLabel}</button></fieldset>}
function SyncTime({provider,attempt,success}:{provider?:CalendarProvider;attempt:string|null;success:string|null}){const tried=attempt??provider?.lastAttemptedSyncAt;const worked=success??provider?.lastSuccessfulSyncAt;return <p className="text-xs text-slate-500">Last synchronized: {worked?new Date(worked).toLocaleString():"Never"}{tried&&!worked?` · Last attempted ${new Date(tried).toLocaleString()}`:""}</p>}
