import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { CalendarConnections } from "./calendar-connections";
import { externalCalendarSessionKey } from "./calendar-service";

const actions=vi.hoisted(()=>({snapshot:vi.fn(),test:vi.fn(),discover:vi.fn(),select:vi.fn(),sync:vi.fn(),status:vi.fn(),connectGoogle:vi.fn(),discoverGoogle:vi.fn(),selectGoogle:vi.fn(),disconnect:vi.fn(),revoke:vi.fn()}));
vi.mock("../calendar-actions",()=>({getCalendarProviderSnapshot:actions.snapshot,testConnection:actions.test,discoverCalendars:actions.discover,selectCalendars:actions.select,synchronizeCalendar:actions.sync,getCalendarSyncStatus:actions.status,connectGoogleCalendar:actions.connectGoogle,discoverGoogleCalendars:actions.discoverGoogle,selectGoogleCalendars:actions.selectGoogle,disconnectProvider:actions.disconnect,revokeProvider:actions.revoke}));
const provider={type:"CALDAV",displayName:"CalDAV",installationConfigured:true,enabled:true,connected:false,authorizationRequired:false,selectedCalendarCount:0,discoveredCalendarCount:0,lastSuccessfulSyncAt:null,lastAttemptedSyncAt:null,providerStatus:"DISCONNECTED",safeMessage:"CalDAV is disconnected.",status:"DISCONNECTED",capabilities:{readEvents:true,writeEvents:false,discovery:true,recurrence:true}};
const redirectUri="http://localhost:9090/api/calendar/providers/GOOGLE/oauth/callback";
const calendar=(id:string,name:string,selected=false)=>({providerType:"CALDAV",calendarId:id,displayName:name,calendarUrl:`/${id}/`,enabled:true,readOnly:true,supportsEvents:true,selected,color:null,description:null});

describe("CalendarConnections",()=>{
  const providers=[{...provider,type:"MANUAL",displayName:"Manual Calendar",status:"CONNECTED"},provider];
  const renderConnections=(values=providers,available=true)=>render(<CalendarConnections initialProviders={values} providersAvailable={available} manualEvents={[]} onEvents={vi.fn()}/>);
  beforeEach(()=>{vi.clearAllMocks();localStorage.clear();sessionStorage.clear();window.history.replaceState({},"","/calendar");actions.snapshot.mockResolvedValue({providers,available:true,message:null});});
  it("shows providers and tests connection with sanitized state",async()=>{actions.test.mockResolvedValue({status:"CONNECTED",message:"CalDAV connection succeeded."});renderConnections();expect(await screen.findByRole("heading",{name:"Manual Calendar"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Test connection"}));expect(await screen.findByText("CalDAV connection succeeded.")).toBeInTheDocument();});
  it("discovers and auto-selects a single read-only calendar",async()=>{actions.discover.mockResolvedValue({calendars:[calendar("work","Work",true)],status:"DISCOVERED",message:"Discovered 1 CalDAV calendar(s).",discoveredAt:new Date().toISOString()});renderConnections([{...provider,status:"CONNECTED"}]);fireEvent.click(await screen.findByRole("button",{name:"Discover calendars"}));expect(await screen.findByText("Work")).toBeInTheDocument();expect(screen.getByText("Read only")).toBeInTheDocument();expect(await screen.findByRole("checkbox",{name:/Work/})).toBeChecked();});
  it("requires and applies selection inside the CalDAV provider",async()=>{const values=[calendar("work","Work"),calendar("personal","Personal")];actions.discover.mockResolvedValue({calendars:values,status:"SELECTION_REQUIRED",message:"Select calendars.",discoveredAt:new Date().toISOString()});actions.select.mockResolvedValue([calendar("work","Work",true),values[1]]);renderConnections([{...provider,status:"CONNECTED",providerStatus:"CONNECTED",connected:true}]);fireEvent.click(await screen.findByRole("button",{name:"Discover calendars"}));const work=await screen.findByRole("checkbox",{name:/Work/});const caldavCard=screen.getByRole("heading",{name:"CalDAV"}).closest("article");expect(caldavCard).toContainElement(work);fireEvent.click(work);fireEvent.click(screen.getByRole("button",{name:"Apply selection"}));expect(await screen.findByText("Calendar selection saved.")).toBeInTheDocument();expect(actions.select).toHaveBeenCalledWith(["work"]);});
  it("shows no-calendar state",async()=>{actions.discover.mockResolvedValue({calendars:[],status:"NO_CALENDARS",message:"No event calendars were discovered.",discoveredAt:new Date().toISOString()});renderConnections([{...provider,status:"CONNECTED"}]);fireEvent.click(await screen.findByRole("button",{name:"Discover calendars"}));expect(await screen.findByText("No CalDAV calendars were discovered.")).toBeInTheDocument();});
  it("synchronizes selected calendars, shows partial state, and stores no credentials",async()=>{actions.discover.mockResolvedValue({calendars:[calendar("work","Work",true)],status:"DISCOVERED",message:"Ready",discoveredAt:new Date().toISOString()});actions.sync.mockResolvedValue({events:[{id:"caldav:1",title:"Review",startTime:"2026-07-20T14:00:00Z",endTime:"2026-07-20T14:30:00Z",busy:true,source:"CALDAV",calendarId:"work"}],errors:[{providerType:"CALDAV",code:"TIMEOUT",message:"Calendar availability may be incomplete."}],calendars:[],synchronizedAt:"2026-07-20T13:00:00Z",partial:true});actions.status.mockResolvedValue({lastAttempt:"2026-07-20T13:00:00Z",lastSuccess:"2026-07-20T12:00:00Z",status:"PARTIAL",message:"Partial",calendars:[]});const onEvents=vi.fn();render(<CalendarConnections initialProviders={[{...provider,status:"CONNECTED"}]} manualEvents={[]} onEvents={onEvents}/>);fireEvent.click(await screen.findByRole("button",{name:"Discover calendars"}));fireEvent.click(await screen.findByRole("button",{name:"Synchronize now"}));await waitFor(()=>expect(onEvents).toHaveBeenCalled());expect(screen.getByText("Calendar availability may be incomplete.")).toBeInTheDocument();expect(screen.getByText(/Last synchronized:/)).not.toHaveTextContent("Never");expect(sessionStorage.getItem(externalCalendarSessionKey)).toContain("Review");expect(localStorage.length).toBe(0);});
  it("shows Google disconnected state and starts backend authorization without browser token storage",async()=>{const values=[...providers,{...provider,type:"GOOGLE",displayName:"Google Calendar",status:"DISCONNECTED",providerStatus:"DISCONNECTED"}];actions.connectGoogle.mockReturnValue(new Promise(()=>{}));renderConnections(values);const connect=await screen.findByRole("button",{name:"Connect Google Calendar"});fireEvent.click(connect);expect(actions.connectGoogle).toHaveBeenCalledOnce();expect(await screen.findByLabelText("Google Calendar status: CONNECTING")).toBeInTheDocument();expect(localStorage.length).toBe(0);expect(sessionStorage.length).toBe(0);});
  it("discovers and durably selects Google calendars",async()=>{const google={...provider,type:"GOOGLE",displayName:"Google Calendar",status:"CONNECTED",providerStatus:"CONNECTED",connected:true};const primary={...calendar("gcal_primary","Primary",true),providerType:"GOOGLE",description:"Primary calendar"};actions.discoverGoogle.mockResolvedValue({calendars:[primary],status:"DISCOVERED",message:"Discovered 1 Google calendar(s).",discoveredAt:new Date().toISOString()});actions.selectGoogle.mockResolvedValue([primary]);renderConnections([google]);fireEvent.click(await screen.findByRole("button",{name:"Discover calendars"}));expect(await screen.findByRole("checkbox",{name:/Primary/})).toBeInTheDocument();expect(screen.getAllByText("Primary").length).toBeGreaterThan(1);fireEvent.click(screen.getByRole("button",{name:"Apply Google selection"}));await waitFor(()=>expect(actions.selectGoogle).toHaveBeenCalledWith(["gcal_primary"]));expect(await screen.findByText("Google calendar selection saved.")).toBeInTheDocument();});

  it("explains disabled Google installation without exposing secret controls",()=>{renderConnections([...providers,{...provider,type:"GOOGLE",displayName:"Google Calendar",installationConfigured:false,enabled:false,status:"DISABLED",providerStatus:"DISABLED",safeMessage:"Google Calendar is not configured for this Wellness Window installation."}]);expect(screen.getByText("Google Calendar is not configured for this Wellness Window installation.")).toBeInTheDocument();fireEvent.click(screen.getByText("Setup instructions"));expect(screen.getByText(redirectUri)).toBeInTheDocument();expect(screen.queryByRole("button",{name:/Connect Google/})).not.toBeInTheDocument();expect(screen.queryByLabelText(/client secret/i)).not.toBeInTheDocument();});

  it("shows a safe cancelled callback and removes callback values from the URL",async()=>{window.history.replaceState({},"","/calendar?oauth=failure&reason=AUTHORIZATION_CANCELLED");renderConnections([...providers,{...provider,type:"GOOGLE",displayName:"Google Calendar"}]);expect(await screen.findByText("Google authorization was cancelled. Try connecting again.")).toBeInTheDocument();expect(window.location.search).toBe("");expect(localStorage.length).toBe(0);expect(sessionStorage.length).toBe(0);});

  it("renders manual-only mode and unavailable recovery without unusable provider actions",()=>{renderConnections([],false);expect(screen.getByText(/Device-local/)).toBeInTheDocument();expect(screen.getByRole("alert")).toHaveTextContent("Manual events can still be used");expect(screen.queryByRole("button",{name:"Connect Google Calendar"})).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Retry calendar connections"})).toBeInTheDocument();});
});
