package com.oneil.wellness.walkplanner.calendar.provider.google;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import com.oneil.wellness.walkplanner.calendar.credential.ProviderCredentialStore;import com.oneil.wellness.walkplanner.calendar.model.*;import com.oneil.wellness.walkplanner.calendar.persistence.*;import java.net.*;import java.util.*;import java.util.concurrent.atomic.AtomicReference;import org.junit.jupiter.api.Test;
class GoogleOAuthServiceTest {
 @Test void authorizationUsesPkceConsumesStateAndStoresTokensWithoutReturningThem(){var config=config();var states=mock(OAuthAuthorizationStateRepository.class);var metadata=mock(OAuthTokenMetadataRepository.class);var connections=mock(ProviderConnectionService.class);var credentials=mock(ProviderCredentialStore.class);var connection=new CalendarProviderConnection(CalendarProviderType.GOOGLE,"Google Calendar",true);when(connections.getOrCreate(any(),anyString(),anyBoolean())).thenReturn(connection);Map<String,String> secrets=new HashMap<>();doAnswer(i->{secrets.put(i.getArgument(1),i.getArgument(2));return null;}).when(credentials).saveSecret(eq(connection.getId()),anyString(),anyString());when(credentials.readSecret(eq(connection.getId()),anyString())).thenAnswer(i->Optional.ofNullable(secrets.get(i.getArgument(1))));doAnswer(i->{secrets.remove(i.getArgument(1));return null;}).when(credentials).deleteSecret(eq(connection.getId()),anyString());AtomicReference<OAuthAuthorizationStateEntity> saved=new AtomicReference<>();when(states.save(any())).thenAnswer(i->{saved.set(i.getArgument(0));return i.getArgument(0);});when(states.findForUpdate(anyString())).thenAnswer(i->Optional.ofNullable(saved.get()));String tokenJson="{\"access_token\":\"access-secret\",\"refresh_token\":\"refresh-secret\",\"expires_in\":3600,\"scope\":\""+GoogleOAuthService.CALENDAR_LIST_SCOPE+" "+GoogleOAuthService.EVENT_SCOPE+"\",\"token_type\":\"Bearer\"}";GoogleHttpTransport http=(m,u,h,b)->new GoogleHttpTransport.Response(200,tokenJson);var service=new GoogleOAuthService(config,http,states,metadata,connections,credentials,"http://localhost:3000/calendar?oauth=success","http://localhost:3000/calendar?oauth=failure");var start=service.begin();assertTrue(start.authorizationUrl().contains("code_challenge_method=S256"));String state=query(start.authorizationUrl(),"state");var result=service.complete("code",state,null);assertTrue(result.successful());assertFalse(result.redirectUrl().contains("secret"));assertEquals("access-secret",secrets.get("access-token"));assertEquals("refresh-secret",secrets.get("refresh-token"));assertFalse(service.complete("code",state,null).successful());}
 @Test void rejectsMissingStateAndCancelledCallback(){var service=minimalService();assertEquals("INVALID_STATE",service.complete("code",null,null).status());}
 private GoogleOAuthService minimalService(){return new GoogleOAuthService(config(),(m,u,h,b)->new GoogleHttpTransport.Response(500,"{}"),mock(OAuthAuthorizationStateRepository.class),mock(OAuthTokenMetadataRepository.class),mock(ProviderConnectionService.class),mock(ProviderCredentialStore.class),"http://localhost:3000/calendar?oauth=success","http://localhost:3000/calendar?oauth=failure");}
 private GoogleCalendarConfiguration config(){var c=new GoogleCalendarConfiguration();c.setEnabled(true);c.setClientId("client");c.setClientSecret("client-secret");c.setRedirectUri(URI.create("http://localhost:9090/api/calendar/providers/GOOGLE/oauth/callback"));c.setAuthorizationUri(URI.create("https://accounts.google.test/auth"));c.setTokenUri(URI.create("https://oauth2.test/token"));return c;}
 private String query(String url,String name){return Arrays.stream(URI.create(url).getRawQuery().split("&")).map(v->v.split("=",2)).filter(v->URLDecoder.decode(v[0],java.nio.charset.StandardCharsets.UTF_8).equals(name)).map(v->URLDecoder.decode(v[1],java.nio.charset.StandardCharsets.UTF_8)).findFirst().orElseThrow();}
}
