import type { NotificationDecision,RecommendationSnapshot,UserSettings,WeatherResponse,CalendarEvent } from "../types";
import { getNotificationDecision,saveRecommendationSnapshot } from "../wellness-actions";
export const notificationStateKey="wellness-window-notifications:v1";let timer:number|null=null;
type DeliveryState={date:string;count:number;lastAt:string|null;fingerprint:string|null};
export function notificationSupport(){if(typeof window==="undefined"||typeof Notification==="undefined")return "UNSUPPORTED" as const;return Notification.permission.toUpperCase() as "DEFAULT"|"GRANTED"|"DENIED";}
export async function requestNotificationPermission(){if(notificationSupport()==="UNSUPPORTED")return "UNSUPPORTED";return (await Notification.requestPermission()).toUpperCase();}
export function recommendationSnapshot(weather:WeatherResponse,events:CalendarEvent[]):RecommendationSnapshot|null{const best=weather.bestWalkingWindow;if(!best||best.noAvailableReason)return null;const hour=weather.hourlyForecast.find(v=>new Date(best.startTime).getTime()>=new Date(v.startTime).getTime()&&new Date(best.startTime).getTime()<new Date(v.startTime).getTime()+3600000);return{timestamp:new Date().toISOString(),score:best.score,recommendedStart:best.startTime,recommendedEnd:best.endTime,temperature:hour?.temperature??weather.current.temperature,wind:hour?.windSpeed??weather.current.windSpeed,humidity:hour?.humidity??weather.current.humidity,aqi:hour?.aqi??weather.environmentalConditions?.aqi??null,uv:hour?.uvIndex??weather.environmentalConditions?.uvIndex??null,calendarAvailable:best.availability==="AVAILABLE"&&!best.conflictingEvent,providerSources:[...new Set(["MANUAL",...events.map(e=>e.source)])],reasonSummary:[...best.positiveReasons,...best.calendarReasons].slice(0,3).join(" ")||best.selectionReason};}
export async function processRecommendation(weather:WeatherResponse,events:CalendarEvent[],settings:UserSettings){const snapshot=recommendationSnapshot(weather,events);if(!snapshot)return null;await saveRecommendationSnapshot(snapshot);if(timer!==null){window.clearTimeout(timer);timer=null;}if(!settings.notificationsEnabled||notificationSupport()!=="GRANTED")return null;const state=loadState();const decision=await getNotificationDecision(snapshot,settings,state.lastAt,state.count);if(decision.eligible&&decision.scheduleAt){const delay=Math.max(0,new Date(decision.scheduleAt).getTime()-Date.now());timer=window.setTimeout(()=>deliver(decision,snapshot),delay);}return decision;}
function deliver(decision:NotificationDecision,snapshot:RecommendationSnapshot){const state=loadState();const fingerprint=`${snapshot.recommendedStart}:${snapshot.score}`;if(state.fingerprint===fingerprint)return;const title=decision.title??"Walking opportunity",body=decision.body??snapshot.reasonSummary,id=btoa(snapshot.recommendedStart).replace(/[^a-zA-Z0-9_-]/g,"").slice(0,100);if("serviceWorker"in navigator){navigator.serviceWorker.ready.then(reg=>reg.showNotification(title,{body,tag:"wellness-window-opportunity",data:{recommendationId:id},actions:[{action:"start",title:"Start walk"},{action:"dismiss",title:"Dismiss"}]} as NotificationOptions)).catch(()=>new Notification(title,{body,tag:"wellness-window-opportunity"}))}else{const notification=new Notification(title,{body,tag:"wellness-window-opportunity"});notification.onclick=()=>{window.focus();window.location.href="/";notification.close()}}const next={date:today(),count:state.count+1,lastAt:new Date().toISOString(),fingerprint};localStorage.setItem(notificationStateKey,JSON.stringify(next));timer=null;}
function loadState():DeliveryState{try{const value=JSON.parse(localStorage.getItem(notificationStateKey)??"null") as DeliveryState|null;if(value?.date===today())return value;}catch{}return{date:today(),count:0,lastAt:null,fingerprint:null};}function today(){return new Date().toISOString().slice(0,10);}
