package com.oneil.wellness.walkplanner.calendar.credential;
import com.oneil.wellness.walkplanner.calendar.persistence.*; import java.nio.charset.StandardCharsets; import java.security.SecureRandom; import java.util.*; import javax.crypto.*; import javax.crypto.spec.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service
public class EncryptedProviderCredentialStore implements ProviderCredentialStore {
 private final ProviderCredentialReferenceRepository references; private final ProviderEncryptedCredentialRepository values; private final byte[] key; private final SecureRandom random=new SecureRandom();
 public EncryptedProviderCredentialStore(ProviderCredentialReferenceRepository r,ProviderEncryptedCredentialRepository v,@Value("${provider.credentials.master-key:}") String encoded){references=r;values=v;key=encoded==null||encoded.isBlank()?null:Base64.getDecoder().decode(encoded);if(key!=null&&key.length!=32)throw new IllegalStateException("Provider credential master key must decode to 32 bytes.");}
 @Transactional public void saveSecret(UUID id,String name,String value){write(id,name,value,false);} @Transactional public void rotateSecret(UUID id,String name,String value){write(id,name,value,true);}
 private void write(UUID id,String name,String secret,boolean rotate){requireKey();var ref=references.findById(new ProviderCredentialReference.Key(id,name)).orElseGet(()->new ProviderCredentialReference(id,name,1));if(rotate)ref.rotate();references.save(ref);byte[] nonce=new byte[12];random.nextBytes(nonce);byte[] cipher=crypt(Cipher.ENCRYPT_MODE,id,name,ref.getCredentialVersion(),nonce,secret.getBytes(StandardCharsets.UTF_8));var stored=values.findById(new ProviderEncryptedCredential.Key(id,name)).orElseGet(()->new ProviderEncryptedCredential(id,name,ref.getCredentialVersion(),nonce,cipher));stored.update(ref.getCredentialVersion(),nonce,cipher);values.save(stored);}
 public Optional<String> readSecret(UUID id,String name){requireKey();return values.findById(new ProviderEncryptedCredential.Key(id,name)).map(v->new String(crypt(Cipher.DECRYPT_MODE,id,name,v.getCredentialVersion(),v.getNonce(),v.getCiphertext()),StandardCharsets.UTF_8));}
 @Transactional public void deleteSecret(UUID id,String name){values.deleteById(new ProviderEncryptedCredential.Key(id,name));references.deleteById(new ProviderCredentialReference.Key(id,name));} @Transactional public void deleteAll(UUID id){values.deleteByProviderConnectionId(id);references.deleteByProviderConnectionId(id);} public boolean exists(UUID id,String name){return values.existsById(new ProviderEncryptedCredential.Key(id,name));}
 private byte[] crypt(int mode,UUID id,String name,int version,byte[] nonce,byte[] input){try{Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(mode,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,nonce));cipher.updateAAD((id+"|"+name+"|"+version).getBytes(StandardCharsets.UTF_8));return cipher.doFinal(input);}catch(AEADBadTagException ex){throw new CredentialStoreException("Credential authentication failed.",ex);}catch(Exception ex){throw new CredentialStoreException("Credential operation failed.",ex);}}
 private void requireKey(){if(key==null)throw new CredentialStoreException("Credential encryption is not configured.");}
 public static class CredentialStoreException extends RuntimeException{public CredentialStoreException(String m){super(m);}public CredentialStoreException(String m,Throwable c){super(m,c);}}
}
